
version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/izzidone
    ports:
       - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=izzidone
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
   
# services:
#   app:
#     build:
#       context: .
#       args:
#         - DEV=true
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./izzidone:/izzidone       

#     command: >
#       sh -c "python manage.py wait_for_db &&
#              python manage.py migrate&&
#              python manage.py runserver 0.0.0.0:8000"
#     environment:
#       - DB_HOST=db
#       - DB_NAME=izzidone
#       - DB_USER=myuser
#       - DB_PASS=mypassword
#     depends_on:
#       - db  



#   db:
#     image: postgres:15-alpine      
#     volumes:
#       - dev-db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=izzidone
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword

# volumes:
#   dev-db-data:           