# Generated by Django 3.2.20 on 2023-08-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Service Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Subservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Subservice Image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('service_button', models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=50, verbose_name='Service Button')),
                ('pricing', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed')], max_length=50, verbose_name='Pricing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Subservice',
                'verbose_name_plural': 'Subservices',
            },
        ),
        migrations.CreateModel(
            name='ChooseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.subservice', verbose_name='Subservice')),
            ],
            options={
                'verbose_name': 'ChooseService',
                'verbose_name_plural': 'ChooseServices',
            },
        ),
    ]
