# Generated by Django 3.2.20 on 2023-08-25 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=30, verbose_name='Certificate')),
                ('image', models.ImageField(upload_to='', verbose_name='Certificate Image')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(max_length=30, verbose_name='Portfolio')),
                ('image', models.ImageField(upload_to='', verbose_name='Portfolio Image')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.AlterField(
            model_name='subservice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name="Professional's Image")),
                ('about', models.TextField(verbose_name='About')),
                ('verified', models.BooleanField(default=True, verbose_name='Verified Profile')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_pro', models.BooleanField(default=False, verbose_name='Top Pro')),
                ('portfolio', models.ImageField(upload_to='', verbose_name='services.Portfolio')),
                ('certificate', models.ManyToManyField(to='services.Certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
            },
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=50, verbose_name='Reviews')),
                ('rating', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Service Rating')),
                ('price', models.CharField(max_length=50, verbose_name='Service Price')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.subservice', verbose_name='Subservice')),
            ],
            options={
                'verbose_name': 'MySkills',
                'verbose_name_plural': 'MySkills',
            },
        ),
        migrations.CreateModel(
            name='AllPros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('filter', models.BooleanField(default=False, verbose_name='Filter')),
                ('all_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.chooseservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'AllPros',
                'verbose_name_plural': 'AllPros',
            },
        ),
    ]
